### ISSUE TITLE
자바맹인데요 ㅠ.ㅠ 어떻게 실행해야 하나요?

### ISSUE THREAD

**Issue by ganadist** [GDG-Korea/gdg_codelab_1403#1]
자바소스는 어떻게 실행해야 하나요?

**Comment by ycha** [comment]
안녕하세요. 지나가던 삽질러 1입니다.

원래라면 오픈소스바닥에서 만인의 공적으로 떠오르고 있는 오라클의 Java 개발도구 ( http://www.oracle.com/technetwork/java/javase/downloads/index.html )를 PC에 내려받아서 개발환경을 꾸며야 합니다.

하지만 왠지 귀찮고 어려울 것 같으니...

![ellipsis](https://f.cloud.github.com/assets/223491/2364754/da897752-a68c-11e3-888f-21b2237585be.jpg)

라고 하면 김화백님한테 맞을꺼 같아서 간단하게 실행하는 방법을 알려드리겠습니다.

http://www.compileonline.com/compile_java_online.php 페이지에서 실행하기를 원하는 자바코드 전체를 "Main class file" 탭에 모두 복사한 다음 "Compile & Execute"버튼을 실행해보세요.

그리고 누군가가 실행 방법을 이렇게 불친절한 방법 말고도 다른 좋은 방법(README 파일 같이 눈에 띄는 곳에 간단한 매뉴얼을 만들기)이 있을텐데 말이죠.

이슈를 생성하면 2점, 매뉴얼을 만들어서 올리면 2점, 적용되면 3점, 닫으면 2점, 총 9점을 손쉽게 얻을 수 있다는 소문도 있습니다.... 하하하. 뭐 그렇다고요...

부디 항상 코드와 함께하기를...

**Comment by ganadist** [comment]
귀찮고 어려울거 같아서 관둘랬는데..

왠지 짤방이 전투력을 상승시키는 절묘한 효과가 있네요.

어쨌든 탭이랑 버튼을 찾느라고 한참 동안 숨바꼭질을 했지만, 결국엔 찾아서 실행에 성공했습니다.

그런데 실행을 해보니 생각했던 거랑 다른 결과 값이 나오네요.. (자바까진 몰라도 피보나치 수열정도는 안다구요!!!)

![image](https://f.cloud.github.com/assets/221114/2364783/63e4755a-a68e-11e3-9d36-26508aa95d03.png)

이왕 알려주신거 조금만 더 가르쳐주세요.

**Comment by ycha** [comment]
코드 내부에 무슨 문제가 있나보군요.

일단 Command Line Arguments에 피보나치 수열의 마지막 항에 해당하는 숫자를 입력하고 실행해야 하는 것으로 보입니다. **매뉴얼을 만드실 분**은 꼭 참조하세요.

![image](https://f.cloud.github.com/assets/221114/2365835/a0397674-a6e1-11e3-93e6-a009e616bb06.png)

실행하는 방법을 알려주는 것이랑, 실행하는 도중에 오류가 발생하는 것은 별도의 문제니깐, 이 이슈는 닫아버리고, 새로 이슈 항목을 만들어서 이야기를 진행하는 것이 좋겠습니다.

제가 이슈를 등록해서 **2등 선물** 을 받는데 유리하게 끌고 가고 싶지만, 선물에 눈이 먼 다른 분들에게 양보하겠습니다. 각 테이블에 계신 분들중 한분씩 나와서 **가위바위보**로 이긴 분에게 4점.. 아니 이슈 등록권을 드리겠습니다.

2등은 소중하니깐요!!!

아. 그리고 ganadist님은 행사 시작 전에 이슈를 올렸기 때문에, 점수 획득은 무효로 취급하겠습니다.

억울하다고요? 억울하면 2등하세요 =33
