### ISSUE TITLE
.class 파일은 repo에 올라오지 않으면 좋겠습니다.

### ISSUE THREAD

**Issue by nurinamu** [GDG-Korea/gdg_codelab_1403#14]
.class파일은 repo에 없으면 좋겠는데.

어떻게 하는거죠? 아시는 분이 있으실텐데 말이죠 ;-)

**Comment by sunglim** [comment]
Working in progress from https://github.com/GDG-Korea/gdg_codelab_1403/pull/13

**Comment by nurinamu** [comment]
.class 파일이 아직도 repo에 남아있네요.

.gitignore만 고쳐지고 rm이 안된 것 같아요!

**Comment by ganadist** [comment]
#44 에서 클래스 파일도 지워졌습니다.
