### ISSUE TITLE
인자로 47이상을 주면 음수값이 나왔다 말았다 합니다.

### ISSUE THREAD

**Issue by ganadist** [GDG-Korea/gdg_codelab_1403#2]
지나가던 어떤 분이 실행하는 방법을 알려주셔서, 이렇게 저렇게 실행해봤는데요.

실행할 때 값을 47보다 크게 주면 출력물에서 음수가 나옵니다.

![image](https://f.cloud.github.com/assets/221114/2367656/8a3b52fe-a770-11e3-8c38-dff646e91391.png)

뭔가 이상한데요. 해결해주세요.

**Comment by gpeddler** [comment]
피보나치 수열값이 int범위를 초과한 것 같습니다.

int fib1
int fib2
int fib3 

을 long 타입으로 바꾸면 우선 int 범위 이상의 결과값을 얻을 수 있을것 같습니다...ㅋㅋㅋㅋㅋ

**Comment by recursivecurry** [comment]
long도 범위가 있으니, 임의의 자리수까지 처리를 하려면 속도가 좀 느리지만 java.math.BigInteger가 낫지 않을까요?
