### ISSUE TITLE
Star 갯수가 너무 적은 것 같습니다.

### ISSUE THREAD

**Issue by grhbit** [GDG-Korea/gdg_codelab_1403#26]
Fork는 34개인데 여러분 Star버튼 눌러주세요!

**Comment by choipd** [comment]
어디에 누르는지 모르시는 분들을 위해서... 
![image](https://f.cloud.github.com/assets/344131/2427800/27436002-ac0b-11e3-84d4-6a5bd6efefb9.png)

**Comment by utrpanic** [comment]
날카로운 지적입니다.

**Comment by seoh** [comment]
+1

**Comment by recursivecurry** [comment]
좋아요.

**Comment by jjuakim** [comment]
@choipd  +1 좋아요

**Comment by Zinccccc** [comment]
눌렀습니다
