### ISSUE TITLE
Test Case가 필요할 것 같습니다.

### ISSUE THREAD

**Issue by grhbit** [GDG-Korea/gdg_codelab_1403#28]
능력자 분들 테스트 자동화 시스템 넣어주세요~

**Comment by JaehyunAhn** [comment]
피보나치는 음의 피보나치 수도 존재합니다. 테스트케이스를 위로 넣어서 OF를 체크하는것도 좋은데, 자동화하실때 음수도 체크할 수 있도록 한 번 생각해주세요. 

자세한 사항은 피보나치의 일반화(http://goo.gl/cvsNYf) 의 negative integers 항목을 참조해주세요.

감사합니다.

**Comment by kyounghee** [comment]
로직이 제대로 되었는지 검증할 수 있는 Unit Test 이었으면 좋겠습니다.
기대결과 결과값이 동일한지 확인할 수 있는 방식이었으면 좋겠네요.
