### ISSUE TITLE
Network is extreamly slow.

### ISSUE THREAD

**Issue by sunglim** [GDG-Korea/gdg_codelab_1403#3]
from here, the network is extreamly slow. 
It is totally impossible to write code !!!

**Comment by ganadist** [comment]
휴대폰 테터링을 공유하는 아름다운 코드랩을 만들어 보아요.

**Comment by jjuakim** [comment]
가능한 AP가 여러개 있으니 옮겨보세요.
"ABLE_" 로 시작하는 AP중 선택하셔서 옮겨보시고요  password는 abler20140310 입니다.

**Comment by ragingwind** [comment]
:+1 :clap:

**Comment by sunglim** [comment]
Thanks @jjuakim
closing then
