### ISSUE TITLE
For loop 보다 Recursion 이 좋을까요? For loop 이 O(n) 인데, recursion 은 계산이 안되네요... -_-...

### ISSUE THREAD

**Issue by tntlym** [GDG-Korea/gdg_codelab_1403#32]

**Comment by enghqii** [comment]
Recursion의 경우 N이 커질때 중복되는 함수 호출이 너무 많을거 같네요

**Comment by sunglim** [comment]
recursion is normally O(2^n).  do you have any good solution to solve fibonacci problem?

**Comment by tntlym** [comment]
@sunglim 착각했습니다. recursion 이 있어도 loop 은 돌려야 하네요.
