### ISSUE TITLE
code indent 가 Tab 랑 Space 가 혼재되어 있습니다 ㅠ

### ISSUE THREAD

**Issue by kyungkoo** [GDG-Korea/gdg_codelab_1403#35]
code 를 보니까 intent 가 tab 이랑 space 가 혼재되어 있습니다. 
한가지로 통일하는게 좋을것 같은데요.. 어떤게 나을까요?

**Comment by grhbit** [comment]
기존 코드가 Space 5개로 되어있었으니 Space로 통일 하는 것이 좋아보입니다.
다른 분들 의견은 어떤가요?

**Comment by Hyemingway** [comment]
동의합니다. 기존 코드대로 space로 하는게 좋을것같아요 :)

**Comment by ragingwind** [comment]
Using http://editorconfig.org/

**Comment by sunglim** [comment]
This is critical. the best way is do not change the original coding convention. (Tab=5space)

**Comment by jjuakim** [comment]
`space` 5개로 readme 파일에 업데이트 하겠습니다.
