### ISSUE TITLE
주석이 깨집니다

### ISSUE THREAD

**Issue by enghqii** [GDG-Korea/gdg_codelab_1403#49]
![asdf](https://f.cloud.github.com/assets/2420985/2427856/de324e1c-ac11-11e3-9bcb-6cd61bbf4ca2.png)

**Comment by grhbit** [comment]
#50 에서 수정하였습니다만 다시 확인해주세요.

**Comment by sunglim** [comment]
Thank you for reporting. 
the culprit is https://github.com/GDG-Korea/gdg_codelab_1403/pull/41
CC @horid121
