### ISSUE TITLE
LICENSE 파일을 추가하는게 좋을것 같습니다.

### ISSUE THREAD

**Issue by kyungkoo** [GDG-Korea/gdg_codelab_1403#51]
LICENSE 가 있으면 좀 더 편안한 마음으로 코드를 사용할 수 있지 않을까요?

**Comment by jjuakim** [comment]
Readme.md 파일에 직접 추가해주셔도 좋을것 같습니다.

**Comment by kyungkoo** [comment]
@jjuakim 아!! readme.me 에도 추가 하는게 좋겠네요! 감사합니다!
