### ISSUE TITLE
README.md 파일 수정

### ISSUE THREAD

**Issue by grhbit** [GDG-Korea/gdg_codelab_1403#54]
https://github.com/GDG-Korea/gdg_codelab_1403#coding-conventions
Indentation 항목 중 Space 4개가 아니라 5개로 변경해주세요.

**Comment by kyounghee** [comment]
결과값이 정상 출력되지 않은 경우에 대해서도 설명해주면 좋을 것 같습니다.
가령 입력값은 2 이상이어야 한다던지.

**Comment by sunglim** [comment]
well. at this time, we need to fix the coding convention. 
Perhaps, we need to listen the opinion from the owner.
@ganadist, do we have to change the indention? or let it be as 5 space?
